# Generated by Django 6.1 on 2026-08-15 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_demand', models.IntegerField()),
                ('recommended_preparation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.IntegerField()),
                ('meals_prepared', models.IntegerField()),
                ('meals_consumed', models.IntegerField()),
                ('holiday', models.BooleanField(default=False)),
                ('rainfall', models.FloatField(default=0.0)),
                ('temperature', models.FloatField(default=25.0)),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('recipient_type', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SurplusFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('storage_hours', models.FloatField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SAFE', 'Safe'), ('UNSAFE', 'Unsafe'), ('REDISTRIBUTED', 'Redistributed')], default='PENDING', max_length=20)),
                ('storage_temperature', models.FloatField(default=4.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_safe', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Redistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('redistribution_date', models.DateField(auto_now_add=True)),
                ('recipient_name', models.CharField(default='Existing Recipient', max_length=100)),
                ('recipient_type', models.CharField(default='Existing Recipient', max_length=100)),
                ('distributed_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.recipient')),
                ('surplus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodapp.surplusfood')),
            ],
        ),
    ]
