# Generated by Django 6.1 on 2026-08-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemandForecast',
        ),
        migrations.RemoveField(
            model_name='redistribution',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='redistribution',
            name='redistribution_date',
        ),
        migrations.RemoveField(
            model_name='surplusfood',
            name='date',
        ),
        migrations.RemoveField(
            model_name='surplusfood',
            name='storage_hours',
        ),
        migrations.RemoveField(
            model_name='surplusfood',
            name='temperature',
        ),
        migrations.AddField(
            model_name='surplusfood',
            name='storage_time_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='Recipient',
        ),
    ]
