# Generated by Django 6.1 on 2026-08-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_demandforecast_recipient_redistribution_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redistribution',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='redistribution',
            name='recipient_type',
        ),
    ]
